version: '3'
services:
  aerospike-server:
    image: aerospike/aerospike-server
    container_name: aerospike-server
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
